#!/usr/bin/env bash

# set -x
set -e

[[ -n $1 ]] || { echo "usage: ./browse chronoscope.db"; exit 1; }

DB="$1"
RQ=$(echo 'select DISTINCT(id) from tick where type="leader";' | sqlite3 $DB)
ENV=${2:-./env}

env() {
    $ENV "$@"
}

for r in $RQ; do
    #env python3 -m chronoscope -d $DB vcd   -v -k $r
    env python3 -m chronoscope -d $DB tree  -k $r
    env python3 -m chronoscope -d $DB chart -k $r
done
